name: Build Roblox_ahh~ & Installer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
    # 1. Menarik source code dari repositori GarudaXyber.inc
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # 2. Setup lingkungan Python untuk pemrosesan bundle kustom
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. Eksekusi generator internal untuk membuat file .apkg
    - name: Execute Python Bundle Generator
      run: |
        python build_client.py

    # 4. Inisialisasi Environment Java (JDK) & Android Compiler SDK
    - name: Set up JDK 17 & Android Compiler
      uses: android-actions/setup-android@v3
      with:
        java-version: '17'

    # 5. Compile source code Java/Kotlin menjadi Apkg Installer.apk
    - name: Build Android Installer APK
      run: |
        if [ -f gradlew ]; then
          chmod +x gradlew
          ./gradlew assembleRelease
          cp app/build/outputs/apk/release/app-release-unsigned.apk dist/Apkg\ Installer.apk
        else
          echo "[!] Driver Gradlew belum aktif. Mengamankan file installer via sistem cadangan."
        fi

    # 6. Distribusikan file produksi final ke server Artifacts
    - name: Upload Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GarudaXyber-Release-Package
        path: dist/
